spring:
  datasource:
    url: jdbc:mysql://localhost:3306/se_integration?serverTimezone=CTT&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

server:
  port: 8082

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql